spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/car?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 3
      filter: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        log-slow-sql: true
        url-pattern:  /*
        exclusions: "*.js,*.png,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        deny: ""
mybatis:
  type-aliases-package:  com.vip.index.domain.entity
  mapper-locations: classpath:mappers/**/*.xml
logging:
  level:
    com.vip.example.mapper: trace